type MetricCategory =
  | "general"
  | "financial"
  | "health"
  | "education"
  | "labour"
  | "demographics"
  | "crime";

export interface MetricDef {
  id: string;
  label: string;
  unit: string;
  category: MetricCategory;
  worldBankCode: string;
  /** Secondary WB code tried if primary is empty */
  fallbackWorldBankCode?: string;
  /** IMF DataMapper indicator id (WEO); merged after WB primary + fallback for null years */
  imfWeoIndicator?: string;
  /** Multiply IMF DataMapper values (e.g. 1e9 when the series is in billions of US$). */
  imfWeoScale?: number;
  /** UNESCO UIS Data API indicator id; merged after WB (+ IMF) for null years only */
  uisIndicatorId?: string;
  formula?: string;
  sourceUrl: string;
  sourceName: string;
  description: string;
}

export const METRICS: MetricDef[] = [
  {
    id: "gdp",
    label: "GDP (Nominal, US$)",
    unit: "US$",
    category: "financial",
    worldBankCode: "NY.GDP.MKTP.CD",
    imfWeoIndicator: "NGDPD",
    imfWeoScale: 1_000_000_000,
    sourceName: "World Bank WDI; IMF WEO (NGDPD, billions US$) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.MKTP.CD",
    description:
      "Gross domestic product in current US dollars. Missing WDI points are filled from IMF WEO nominal GDP (NGDPD), converted from billions of US dollars.",
    formula: "GDP = C + I + G + (X − M)",
  },
  {
    id: "gdp_per_capita",
    label: "GDP per capita (Nominal, US$)",
    unit: "US$",
    category: "financial",
    worldBankCode: "NY.GDP.PCAP.CD",
    imfWeoIndicator: "NGDPDPC",
    sourceName: "World Bank WDI; IMF WEO (NGDPDPC) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.PCAP.CD",
    description:
      "GDP divided by midyear population. Missing WDI points are filled from IMF WEO GDP per capita, current prices (NGDPDPC), where published.",
    formula: "GDP per capita = GDP / Population",
  },
  {
    id: "gdp_growth",
    label: "GDP growth (annual %)",
    unit: "%",
    category: "financial",
    worldBankCode: "NY.GDP.MKTP.KD.ZG",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG",
    description: "Annual percentage growth rate of GDP at constant prices.",
  },
  {
    id: "population",
    label: "Population, total",
    unit: "people",
    category: "demographics",
    worldBankCode: "SP.POP.TOTL",
    imfWeoIndicator: "LP",
    imfWeoScale: 1_000_000,
    sourceName: "World Bank WDI; IMF WEO population (LP, millions) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/SP.POP.TOTL",
    description:
      "Total population based on census and WPP estimates. Missing WDI points are filled from IMF WEO population (LP), converted from millions of people.",
  },
  {
    id: "gov_debt_pct_gdp",
    label: "Central government debt, total (% of GDP)",
    unit: "% of GDP",
    category: "financial",
    worldBankCode: "GC.DOD.TOTL.GD.ZS",
    fallbackWorldBankCode: "GC.DOD.TOTL.CN",
    imfWeoIndicator: "GGXWDG_NGDP",
    sourceName: "World Bank WDI; IMF WEO (DataMapper) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/GC.DOD.TOTL.GD.ZS",
    description:
      "Debt of central government as share of GDP (WDI). Null years are filled from IMF WEO general government gross debt (% of GDP), DataMapper series GGXWDG_NGDP, where published.",
    formula: "Debt / GDP × 100",
  },
  {
    id: "inflation",
    label: "Inflation, consumer prices (annual %)",
    unit: "%",
    category: "financial",
    worldBankCode: "FP.CPI.TOTL.ZG",
    imfWeoIndicator: "PCPIPCH",
    sourceName: "World Bank WDI; IMF WEO (PCPIPCH) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG",
    description:
      "Inflation from WDI consumer price index. Null years are filled from IMF WEO inflation, average consumer prices (PCPIPCH), where published.",
  },
  {
    id: "interest_real",
    label: "Real interest rate (%)",
    unit: "%",
    category: "financial",
    worldBankCode: "FR.INR.RINR",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/FR.INR.RINR",
    description: "Real interest rate from World Bank WDI where reported.",
  },
  {
    id: "unemployment_ilo",
    label: "Unemployment, total (% of labour force) — modeled ILO",
    unit: "%",
    category: "labour",
    worldBankCode: "SL.UEM.TOTL.ZS",
    fallbackWorldBankCode: "SL.UEM.TOTL.NE.ZS",
    imfWeoIndicator: "LUR",
    sourceName: "World Bank WDI / ILO modeled; IMF WEO (LUR) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/SL.UEM.TOTL.ZS",
    description:
      "Share of labour force without work but available. National-estimate series SL.UEM.TOTL.NE.ZS is used when the modeled ILO series is null. Remaining gaps use IMF WEO unemployment rate (LUR).",
  },
  {
    id: "poverty_headcount",
    label: "Poverty headcount ratio at $2.15 a day (2017 PPP)",
    unit: "%",
    category: "financial",
    worldBankCode: "SI.POV.DDAY",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SI.POV.DDAY",
    description: "Population living below international poverty line.",
  },
  {
    id: "life_expectancy",
    label: "Life expectancy at birth, total (years)",
    unit: "years",
    category: "health",
    worldBankCode: "SP.DYN.LE00.IN",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SP.DYN.LE00.IN",
    description:
      "Average years a newborn would live under current mortality. Where the total series is null, the global table may use the mean of male (SP.DYN.LE00.MA.IN) and female (SP.DYN.LE00.FE.IN) life expectancy for the same year.",
  },
  {
    id: "mortality_under5",
    label: "Mortality rate, under-5 (per 1,000 live births)",
    unit: "per 1,000",
    category: "health",
    worldBankCode: "SH.DYN.MORT",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SH.DYN.MORT",
    description:
      "Probability of dying before age five per 1,000 births. Where the total series is null, the global table may use the mean of male (SH.DYN.MORT.MA) and female (SH.DYN.MORT.FE) under-five mortality rates.",
  },
  {
    id: "literacy_adult",
    label: "Literacy rate, adult total (% ages 15+)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.ADT.LITR.ZS",
    uisIndicatorId: "LR.GALP.AG15T99",
    sourceName: "World Bank WDI; UNESCO UIS API (gap-fill)",
    sourceUrl: "https://data.worldbank.org/indicator/SE.ADT.LITR.ZS",
    description:
      "Adult literacy from UIS via WDI. Null years may be filled from UIS LR.GALP.AG15T99 (GALP model estimates).",
  },
  {
    id: "school_primary_completion",
    label: "Primary completion rate, total (% of relevant age group)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.PRM.CMPT.ZS",
    uisIndicatorId: "CR.1",
    sourceName: "World Bank WDI; UNESCO UIS API (gap-fill)",
    sourceUrl: "https://data.worldbank.org/indicator/SE.PRM.CMPT.ZS",
    description:
      "WDI uses gross intake ratio to last grade of primary; UIS gap-fill uses CR.1 (completion rate, primary). Methodology can differ slightly.",
  },
  {
    id: "enrollment_secondary",
    label: "School enrollment, secondary (% gross)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.SEC.ENRR",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.SEC.ENRR",
    description: "Total secondary enrollment regardless of age.",
  },
  {
    id: "teachers_primary",
    label: "Pupil-teacher ratio, primary",
    unit: "pupils per teacher",
    category: "education",
    worldBankCode: "SE.PRM.ENRL.TC.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.PRM.ENRL.TC.ZS",
    description: "Average pupils per teacher in primary education.",
  },
  {
    id: "labour_force_participation",
    label: "Labor force participation rate, total (% pop 15+)",
    unit: "%",
    category: "labour",
    worldBankCode: "SL.TLF.ACTI.ZS",
    sourceName: "World Bank WDI / ILO modeled",
    sourceUrl: "https://data.worldbank.org/indicator/SL.TLF.ACTI.ZS",
    description: "Proportion of working-age population in labour force.",
  },
  {
    id: "pop_age_0_14",
    label: "Population ages 0-14 (% of total)",
    unit: "%",
    category: "demographics",
    worldBankCode: "SP.POP.0014.TO.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SP.POP.0014.TO.ZS",
    description: "Youth dependency proxy — share under 15.",
  },
  {
    id: "pop_age_65_plus",
    label: "Population ages 65+ (% of total)",
    unit: "%",
    category: "demographics",
    worldBankCode: "SP.POP.65UP.TO.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SP.POP.65UP.TO.ZS",
    description: "Aging indicator — share 65 and older.",
  },
  {
    id: "gdp_ppp",
    label: "GDP (PPP, Intl$)",
    unit: "Intl$",
    category: "financial",
    worldBankCode: "NY.GDP.MKTP.PP.CD",
    imfWeoIndicator: "PPPGDP",
    imfWeoScale: 1_000_000_000,
    sourceName: "World Bank WDI; IMF WEO (PPPGDP, billions intl$) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.MKTP.PP.CD",
    description:
      "GDP converted to international dollars using PPP rates. Missing WDI points are filled from IMF WEO GDP at PPP (PPPGDP), converted from billions of international dollars.",
    formula: "GDP (PPP) = GDP × PPP conversion factor",
  },
  {
    id: "gdp_per_capita_ppp",
    label: "GDP per capita (PPP, Intl$)",
    unit: "Intl$",
    category: "financial",
    worldBankCode: "NY.GDP.PCAP.PP.CD",
    imfWeoIndicator: "PPPPC",
    sourceName: "World Bank WDI; IMF WEO (PPPPC) for gaps",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD",
    description:
      "GDP per person in international dollars (PPP). Missing WDI points are filled from IMF WEO GDP per capita at PPP (PPPPC), where published.",
    formula: "GDP per capita (PPP) = GDP (PPP) / Population",
  },
  {
    id: "gni_per_capita_atlas",
    label: "GNI per capita, Atlas method (current US$)",
    unit: "US$",
    category: "financial",
    worldBankCode: "NY.GNP.PCAP.CD",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GNP.PCAP.CD",
    description:
      "Gross national income per person, Atlas method (current US$). The World Bank uses this series (with annual thresholds) for operational income classifications (low / lower-middle / upper-middle / high income). The Country API income group is the authoritative bucket label; this series is the underlying per-capita magnitude.",
  },
  {
    id: "gov_debt_usd",
    label: "Central government debt, total (current US$)",
    unit: "US$",
    category: "financial",
    worldBankCode: "GC.DOD.TOTL.CD",
    sourceName: "World Bank WDI; derived where level series is missing",
    sourceUrl: "https://data.worldbank.org/indicator/GC.DOD.TOTL.CD",
    description:
      "Outstanding central government debt in current US dollars (WDI GC.DOD.TOTL.CD). Where that level series has no value, the backend estimates US$ debt as (government debt % of GDP ÷ 100) × nominal GDP (US$), using the same blended debt-% series as the Gov. debt (% GDP) metric (WDI plus IMF WEO gap-fill).",
    formula: "Debt (US$) ≈ (Debt % GDP / 100) × GDP (nominal US$) when direct WDI level is missing",
  },
  {
    id: "lending_rate",
    label: "Lending interest rate (%)",
    unit: "%",
    category: "financial",
    worldBankCode: "FR.INR.LEND",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/FR.INR.LEND",
    description: "Bank lending rate to prime borrowers.",
  },
  {
    id: "poverty_national",
    label: "Poverty headcount ratio at national poverty lines (% of population)",
    unit: "%",
    category: "financial",
    worldBankCode: "SI.POV.NAHC",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SI.POV.NAHC",
    description: "Population below national poverty lines.",
  },
  {
    id: "maternal_mortality",
    label: "Maternal mortality ratio (per 100,000 live births)",
    unit: "per 100,000",
    category: "health",
    worldBankCode: "SH.STA.MMRT",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SH.STA.MMRT",
    description: "Annual number of maternal deaths per 100,000 live births.",
  },
  {
    id: "undernourishment",
    label: "Prevalence of undernourishment (% of population)",
    unit: "%",
    category: "health",
    worldBankCode: "SN.ITK.DEFC.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SN.ITK.DEFC.ZS",
    description: "Population in a state of undernourishment.",
  },
  {
    id: "birth_rate",
    label: "Birth rate, crude (per 1,000 people)",
    unit: "per 1,000",
    category: "health",
    worldBankCode: "SP.DYN.CBRT.IN",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SP.DYN.CBRT.IN",
    description: "Annual live births per 1,000 population (midyear estimate).",
  },
  {
    id: "tb_incidence",
    label: "Incidence of tuberculosis (per 100,000 people)",
    unit: "per 100,000",
    category: "health",
    worldBankCode: "SH.TBS.INCD",
    sourceName: "World Bank WDI (WHO Global TB Programme)",
    sourceUrl: "https://data.worldbank.org/indicator/SH.TBS.INCD",
    description:
      "Estimated new and relapse tuberculosis cases per 100,000 population (morbidity burden proxy).",
  },
  {
    id: "uhc_service_coverage",
    label: "UHC service coverage index (0-100)",
    unit: "index",
    category: "health",
    worldBankCode: "SH.UHC.SRVS.CV.XD",
    sourceName: "World Bank WDI (WHO/World Bank UHC monitoring)",
    sourceUrl: "https://data.worldbank.org/indicator/SH.UHC.SRVS.CV.XD",
    description:
      "Universal health coverage service coverage index (coverage of essential services on a 0-100 scale).",
  },
  {
    id: "hospital_beds",
    label: "Hospital beds (per 1,000 people)",
    unit: "per 1,000",
    category: "health",
    worldBankCode: "SH.MED.BEDS.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SH.MED.BEDS.ZS",
    description: "Hospital beds available per 1,000 people.",
  },
  {
    id: "physicians_density",
    label: "Physicians (per 1,000 people)",
    unit: "per 1,000",
    category: "health",
    worldBankCode: "SH.MED.PHYS.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SH.MED.PHYS.ZS",
    description: "Medical doctors per 1,000 people.",
  },
  {
    id: "nurses_midwives_density",
    label: "Nurses and midwives (per 1,000 people)",
    unit: "per 1,000",
    category: "health",
    worldBankCode: "SH.MED.NUMW.P3",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SH.MED.NUMW.P3",
    description: "Nurses and midwives per 1,000 people.",
  },
  {
    id: "immunization_dpt",
    label: "Immunization, DPT (% of children ages 12-23 months)",
    unit: "%",
    category: "health",
    worldBankCode: "SH.IMM.IDPT",
    sourceName: "World Bank WDI (WHO/UNICEF estimates)",
    sourceUrl: "https://data.worldbank.org/indicator/SH.IMM.IDPT",
    description: "Share of children ages 12-23 months who received DPT immunization.",
  },
  {
    id: "immunization_measles",
    label: "Immunization, measles (% of children ages 12-23 months)",
    unit: "%",
    category: "health",
    worldBankCode: "SH.IMM.MEAS",
    sourceName: "World Bank WDI (WHO/UNICEF estimates)",
    sourceUrl: "https://data.worldbank.org/indicator/SH.IMM.MEAS",
    description: "Share of children ages 12-23 months who received measles immunization.",
  },
  {
    id: "health_expenditure_gdp",
    label: "Current health expenditure (% of GDP)",
    unit: "% of GDP",
    category: "health",
    worldBankCode: "SH.XPD.CHEX.GD.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SH.XPD.CHEX.GD.ZS",
    description: "Current health expenditure as a share of GDP.",
  },
  {
    id: "smoking_prevalence",
    label: "Smoking prevalence, total (ages 15+)",
    unit: "%",
    category: "health",
    worldBankCode: "SH.PRV.SMOK",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SH.PRV.SMOK",
    description: "Prevalence of current tobacco smoking among people ages 15 and above.",
  },
  {
    id: "oosc_primary",
    label: "Out-of-school rate for children of primary school age (%)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.PRM.OOSC.ZS",
    uisIndicatorId: "ROFST.1.CP",
    sourceName: "World Bank WDI; UNESCO UIS API (gap-fill)",
    sourceUrl: "https://data.worldbank.org/indicator/SE.PRM.OOSC.ZS",
    description:
      "Share of primary-school-age children out of school. UIS fallback: ROFST.1.CP. Global table may approximate OOSC as 100% minus adjusted net primary enrollment (SE.PRM.NENR) when both are still null.",
  },
  {
    id: "oosc_secondary",
    label: "Out-of-school rate for adolescents of lower secondary school age (%)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.SEC.OOSC.ZS",
    uisIndicatorId: "ROFST.2.CP",
    sourceName: "World Bank WDI; UNESCO UIS API (gap-fill)",
    sourceUrl: "https://data.worldbank.org/indicator/SE.SEC.OOSC.ZS",
    description: "Share of lower-secondary-age adolescents out of school. UIS fallback: ROFST.2.CP.",
  },
  {
    id: "oosc_tertiary",
    label: "Out-of-school rate for youth of upper secondary school age (%)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.TER.OOSC.ZS",
    uisIndicatorId: "ROFST.3.CP",
    sourceName: "World Bank WDI; UNESCO UIS API (gap-fill)",
    sourceUrl: "https://data.worldbank.org/indicator/SE.TER.OOSC.ZS",
    description:
      "Share of upper-secondary-age youth out of school. UIS fallback: ROFST.3.CP. Global table may approximate OOSC as 100% minus gross tertiary enrollment (SE.TER.ENRR, capped at 100%) when both are still null.",
  },
  {
    id: "completion_secondary",
    label: "Lower secondary completion rate, total (% of relevant age group)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.SEC.CMPT.ZS",
    uisIndicatorId: "CR.2",
    sourceName: "World Bank WDI; UNESCO UIS API (gap-fill)",
    sourceUrl: "https://data.worldbank.org/indicator/SE.SEC.CMPT.ZS",
    description: "Gross completion ratio for lower secondary. UIS fallback: CR.2.",
  },
  {
    id: "completion_tertiary",
    label: "Gross graduation ratio, tertiary education",
    unit: "%",
    category: "education",
    worldBankCode: "SE.TER.GRAD.ZS",
    uisIndicatorId: "GGR.6T7",
    sourceName: "World Bank WDI; UNESCO UIS API (gap-fill)",
    sourceUrl: "https://data.worldbank.org/indicator/SE.TER.GRAD.ZS",
    description:
      "Tertiary graduation ratio. UIS fallback GGR.6T7 covers first-degree programmes (ISCED 6–7); scope may differ from WDI.",
  },
  {
    id: "reading_proficiency",
    label: "Learning poverty: reading (%)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.LPV.PRIM",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.LPV.PRIM",
    description: "Share of children at end-of-primary age below minimum reading proficiency.",
  },
  {
    id: "gpi_primary",
    label: "GPI proxy — school enrollment, primary (gross), gender parity index",
    unit: "index",
    category: "education",
    worldBankCode: "SE.ENR.PRIM.FM.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.ENR.PRIM.FM.ZS",
    description: "Ratio of female to male gross enrollment in primary education.",
  },
  {
    id: "gpi_secondary",
    label: "GPI proxy — school enrollment, secondary (gross), gender parity index",
    unit: "index",
    category: "education",
    worldBankCode: "SE.ENR.SEC.FM.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.ENR.SEC.FM.ZS",
    description: "Ratio of female to male gross enrollment in secondary education.",
  },
  {
    id: "gpi_tertiary",
    label: "GPI proxy — school enrollment, tertiary (gross), gender parity index",
    unit: "index",
    category: "education",
    worldBankCode: "SE.ENR.TER.FM.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.ENR.TER.FM.ZS",
    description: "Ratio of female to male gross enrollment in tertiary education.",
  },
  {
    id: "trained_teachers_pri",
    label: "Trained teachers in primary education (% of total teachers)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.PRM.TCAQ.LO.GE.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.PRM.TCAQ.LO.GE.ZS",
    description: "Share of primary teachers meeting national training standards.",
  },
  {
    id: "trained_teachers_sec",
    label: "Trained teachers in lower secondary education (% of total teachers)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.SEC.TCAQ.LO.GE.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.SEC.TCAQ.LO.GE.ZS",
    description: "Share of lower secondary teachers meeting training standards.",
  },
  {
    id: "trained_teachers_ter",
    label: "Trained teachers in upper secondary education (% of total teachers)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.TER.TCAQ.LO.GE.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.TER.TCAQ.LO.GE.ZS",
    description: "Share of upper secondary teachers meeting training standards.",
  },
  {
    id: "edu_expenditure_gdp",
    label: "Government expenditure on education, total (% of GDP)",
    unit: "% of GDP",
    category: "education",
    worldBankCode: "SE.XPD.TOTL.GD.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.XPD.TOTL.GD.ZS",
    description: "Public spending on education as share of GDP.",
  },
  {
    id: "enrollment_primary_pct",
    label: "School enrollment, primary (% gross)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.PRM.ENRR",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.PRM.ENRR",
    description: "Gross enrollment ratio in primary education.",
  },
  {
    id: "enrollment_tertiary_pct",
    label: "School enrollment, tertiary (% gross)",
    unit: "%",
    category: "education",
    worldBankCode: "SE.TER.ENRR",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.TER.ENRR",
    description: "Gross enrollment ratio in tertiary education.",
  },
  {
    id: "enrollment_primary_count",
    label: "Enrolment in primary education, both sexes (number)",
    unit: "people",
    category: "education",
    worldBankCode: "SE.PRM.ENRL",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.PRM.ENRL",
    description: "Total students enrolled in primary education.",
  },
  {
    id: "enrollment_secondary_count",
    label: "Enrolment in secondary education, both sexes (number)",
    unit: "people",
    category: "education",
    worldBankCode: "SE.SEC.ENRL",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.SEC.ENRL",
    description: "Total students enrolled in secondary education.",
  },
  {
    id: "enrollment_tertiary_count",
    label: "Enrolment in tertiary education, all programmes, both sexes (number)",
    unit: "people",
    category: "education",
    worldBankCode: "SE.TER.ENRL",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.TER.ENRL",
    description: "Total students enrolled in tertiary education.",
  },
  {
    id: "teachers_primary_count",
    label: "Teachers in primary education, total",
    unit: "people",
    category: "education",
    worldBankCode: "SE.PRM.TCHR",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.PRM.TCHR",
    description: "Total teachers in primary education.",
  },
  {
    id: "teachers_secondary_count",
    label: "Teachers in secondary education, total",
    unit: "people",
    category: "education",
    worldBankCode: "SE.SEC.TCHR",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.SEC.TCHR",
    description: "Total teachers in secondary education.",
  },
  {
    id: "teachers_tertiary_count",
    label: "Teachers in tertiary education programmes, total",
    unit: "people",
    category: "education",
    worldBankCode: "SE.TER.TCHR",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SE.TER.TCHR",
    description: "Total teachers in tertiary education.",
  },
  {
    id: "pop_15_64_pct",
    label: "Population ages 15-64 (% of total)",
    unit: "%",
    category: "demographics",
    worldBankCode: "SP.POP.1564.TO.ZS",
    sourceName: "World Bank WDI",
    sourceUrl: "https://data.worldbank.org/indicator/SP.POP.1564.TO.ZS",
    description: "Working-age population share.",
  },
  {
    id: "labor_force_total",
    label: "Labor force, total",
    unit: "people",
    category: "labour",
    worldBankCode: "SL.TLF.TOTL.IN",
    sourceName: "World Bank WDI / ILO modeled",
    sourceUrl: "https://data.worldbank.org/indicator/SL.TLF.TOTL.IN",
    description: "Total economically active population.",
  },
  {
    id: "homicide_rate",
    label: "Intentional homicides (per 100,000 people)",
    unit: "per 100,000",
    category: "crime",
    worldBankCode: "VC.IHR.PSRC.P5",
    sourceName: "World Bank WDI (UNODC International Homicide Statistics)",
    sourceUrl: "https://data.worldbank.org/indicator/VC.IHR.PSRC.P5",
    description:
      "Unlawful death purposefully inflicted on a person by another (excludes armed conflict). Sourced from UN Office on Drugs and Crime (UNODC) via criminal justice records, public health data, and UN crime surveys.",
  },
  {
    id: "homicide_rate_female",
    label: "Intentional homicides, female (per 100,000 female)",
    unit: "per 100,000",
    category: "crime",
    worldBankCode: "VC.IHR.PSRC.FE.P5",
    sourceName: "World Bank WDI (UNODC International Homicide Statistics)",
    sourceUrl: "https://data.worldbank.org/indicator/VC.IHR.PSRC.FE.P5",
    description: "Female intentional homicide rate per 100,000 female population (UNODC via WDI).",
  },
  {
    id: "homicide_rate_male",
    label: "Intentional homicides, male (per 100,000 male)",
    unit: "per 100,000",
    category: "crime",
    worldBankCode: "VC.IHR.PSRC.MA.P5",
    sourceName: "World Bank WDI (UNODC International Homicide Statistics)",
    sourceUrl: "https://data.worldbank.org/indicator/VC.IHR.PSRC.MA.P5",
    description: "Male intentional homicide rate per 100,000 male population (UNODC via WDI).",
  },
  {
    id: "gbv_women_pct",
    label: "Women subjected to physical and/or sexual violence in last 12 months (% of ever-partnered women ages 15-49)",
    unit: "%",
    category: "crime",
    worldBankCode: "SG.VAW.1549.ZS",
    sourceName: "World Bank WDI (UN/WHO household surveys)",
    sourceUrl: "https://data.worldbank.org/indicator/SG.VAW.1549.ZS",
    description:
      "Share of ever-partnered women ages 15–49 who experienced physical and/or sexual violence by a current or former intimate partner in the past 12 months.",
  },
  {
    id: "idp_conflict_violence",
    label: "Internally displaced persons, new displacement associated with conflict and violence (number of cases)",
    unit: "cases",
    category: "crime",
    worldBankCode: "VC.IDP.NWCV",
    sourceName: "World Bank WDI (Internal Displacement Monitoring Centre)",
    sourceUrl: "https://data.worldbank.org/indicator/VC.IDP.NWCV",
    description:
      "New internal displacements triggered by conflict and violence during the reference year (IDMC via WDI).",
  },
  {
    id: "battle_related_deaths",
    label: "Battle-related deaths (number of people)",
    unit: "people",
    category: "crime",
    worldBankCode: "VC.BTL.DETH",
    sourceName: "World Bank WDI (Uppsala Conflict Data Program)",
    sourceUrl: "https://data.worldbank.org/indicator/VC.BTL.DETH",
    description:
      "Fatalities from organized armed conflict during the year (UCDP Battle-Related Deaths Dataset via WDI).",
  },
  {
    id: "rule_of_law_wgi",
    label: "Rule of Law — governance estimate (approx. -2.5 to +2.5)",
    unit: "index",
    category: "crime",
    worldBankCode: "GOV_WGI_RL_EST",
    sourceName: "World Bank WDI (Worldwide Governance Indicators)",
    sourceUrl: "https://data.worldbank.org/indicator/GOV_WGI_RL_EST",
    description:
      "Perceptions of confidence in and adherence to the rules of society — contract enforcement, property rights, police, courts, and crime (World Bank WGI). Higher is better.",
  },
  {
    id: "political_stability_wgi",
    label: "Political Stability — governance estimate (approx. -2.5 to +2.5)",
    unit: "index",
    category: "crime",
    worldBankCode: "GOV_WGI_PV_EST",
    sourceName: "World Bank WDI (Worldwide Governance Indicators)",
    sourceUrl: "https://data.worldbank.org/indicator/GOV_WGI_PV_EST",
    description:
      "Likelihood that the government will be destabilized or overthrown by violence or terrorism (World Bank WGI). Higher is more stable.",
  },
  {
    id: "corruption_control_wgi",
    label: "Control of Corruption — governance estimate (approx. -2.5 to +2.5)",
    unit: "index",
    category: "crime",
    worldBankCode: "GOV_WGI_CC_EST",
    sourceName: "World Bank WDI (Worldwide Governance Indicators)",
    sourceUrl: "https://data.worldbank.org/indicator/GOV_WGI_CC_EST",
    description:
      "Extent to which public power is exercised for private gain, including petty and grand corruption (World Bank WGI). Higher is better.",
  },
];

export const METRIC_BY_ID = Object.fromEntries(METRICS.map((m) => [m.id, m]));
